#!/bin/sh
#
#
#	SCCS id Keywords             @(#)  300.2 date 11/17/91 daxcad_plotter_script 
#
#
#	Practical Technology 1990 DAXCAD
#
#	A general purpose spooler program for daxcad
#	This script is exec'd from DAXCAD passing a plotter type
#	and plot file name. You can add pre/post processing facilities
#	without adding to DAXCAD source.
#
#
#
#
if [ $# -lt 2 -o $# -gt 3 ]
then
	echo $0 : bad arg count
	exit 1
fi

MODEL=$2
PLOTFILE=$1
if [ $# -eq 3 ] ; then
        COPIES=$3
else
        COPIES=1
fi

echo -n "Plotting $COPIES copies of $PLOTFILE to plotter: "

case $MODEL in

	1)	echo 'HP7475'
                ;;
		
	2)	echo 'HP7585B ( Sheet Feed )'
		;;

	3)	echo 'Gould 6320'
		;;

	4)	echo 'Benson 1625/45 (Z80) (VDF,TIM100)'
		;;

	5)	echo 'HP 7550'
		;;

	6)	echo 'ROLAND A2'
		;;

	7)	echo 'Calcomp '
		;;

	8)	echo 'HP 7580B'
		;;

	9)	echo 'Hitachi A3/A4'
		;;

	10)	echo 'Benson 1302  (ISDP)'
		;;

	11)	echo 'Gerber Photoplotter'
		;;

	12)	echo 'HP 7586B Roll Feed'
		;;

	13)	echo 'Versatec '
                DEVICE=`vp_default`
                plot40 -c"$COPIES" -P"$DEVICE" $PLOTFILE
		;;

	14)	echo 'Postscript (300 dpi)'
                DEVICE=`ps_default`
                lpr -#"$COPIES" -P"$DEVICE" <$PLOTFILE
		;;

	15)	echo 'Roland  DPX 3300'
		;;

	16)	echo 'Houston DMP'
		;;

	17)	echo 'Interleaf ( Never used for immediate )'
		;;

	18)	echo 'HP7885B'
		;;

	*)
		echo "Unknown plotter. Model no. $MODEL"
		echo
		exit 1
		;;
esac

echo
