C
C     @(#)  412.1 date 6/11/92 obswin.inc 
C
C
C     Filename    : obswin.inc
C     Version     : 412.1
C     Retrieved   : 92/06/12 15:15:31
C     Last change : 92/06/11 14:36:55
C
C     Copyright : Practical Technology International Limited  
C     File :- obswin.inc
C
C     DAXCAD FORTRAN 77 Include file
C
C
      LOGICAL BATCH_AQ
      LOGICAL UNOBSCURED
      LOGICAL GR_LOCK

      COMMON/OBSWL/BATCH_AQ,UNOBSCURED,GR_LOCK












































