C
C     @(#)  412.1 date 6/11/92 prints.inc 
C
C
C     Filename    : prints.inc
C     Version     : 412.1
C     Retrieved   : 92/06/12 15:15:34
C     Last change : 92/06/11 14:38:33
C
C     Copyright : Practical Technology Limited  
C     File :- prints.inc
C
C     DAXCAD FORTRAN 77 Include file
C
C
C     |-----------------------------------------------------------------|
C
C
C     this routine contains all the common definitions
C     for the DCPRNx routines
      INTEGER*4 UNT,TOKNUM,MAXTOC
      CHARACTER*80 BUFF
      COMMON/UNITS/UNT,MAXTOC

