C
C     @(#)  412.1 date 6/11/92 typed.inc 
C
C
C     Filename    : typed.inc
C     Version     : 412.1
C     Retrieved   : 92/06/12 15:15:51
C     Last change : 92/06/11 14:42:31
C
C     Copyright : Practical Technology Limited  
C     File :- typed.inc
C
C     DAXCAD FORTRAN 77 Include file
C
C
C     |-----------------------------------------------------------------|
C
C
      CHARACTER TMPBUF*80
      COMMON /C1/TMPBUF
