C
C     @(#)  412.1 date 6/11/92 wrtinlf.inc 
C
C
C     Filename    : wrtinlf.inc
C     Version     : 412.1
C     Retrieved   : 92/06/12 15:15:56
C     Last change : 92/06/11 14:44:18
C
C     Copyright : Practical Technology Limited  
C     File :- wrtinlf.inc
C
C     DAXCAD FORTRAN 77 Include file
C
C
C     |-----------------------------------------------------------------|
C
C     Temporary include to save fucking around recompiling everything
C     and its grany.
C
      CHARACTER INTFLG*1
      COMMON/INTFLG/INTFLG

      INTEGER ROTTXT
      COMMON/ROTTX/ROTTXT
